### ISSUE TITLE
withTiming should be withSpring

### ISSUE THREAD

**Issue by efstathiosntonas** [mehuljetani/react-native-custom-animated-accordion#1]
Hi, thank you for this lib.

This:

* https://github.com/mehuljetani/react-native-custom-animated-accordion/blob/e6b02d99a100223ca548aced402c239527c52e7c/src/Accordion.tsx#L58-L61

should be `withSpring`

This config does not exist in `withTiming` but only on `withSpring`:

` damping: 5,
   stiffness: 100,
`

**Comment by mehuljetani** [comment]
"Thanks for the suggestion! I see that damping and stiffness are parameters specific to withSpring.I Will Fix this in new update.
